select * from customer 
-- Total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- Customers who used discounts but spent more than the average purchase amount
SELECT customer_id, purchase_amount_usd FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount_usd >
    (SELECT AVG(purchase_amount_usd) FROM customer);

-- Top products ranked by average review rating
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Average purchase amount for each shipping type
SELECT shipping_type, AVG(purchase_amount_usd) AS avg_purchase_amount
FROM customer
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;

-- Top 10 customers based on total spending
SELECT customer_id, SUM(purchase_amount_usd) AS total_spent
FROM customer
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- Customer count, average spend and total revenue by subscription status
SELECT subscription_status,
    COUNT(*) AS total_customers,
    AVG(purchase_amount_usd) AS avg_spend,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Average review rating for each category
SELECT category, AVG(review_rating) AS avg_rating FROM customer
GROUP BY category
ORDER BY avg_rating DESC;

-- Discount usage percentage calculated per product
SELECT item_purchased,
    COUNT(*) AS total_orders,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_orders,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Customer segmentation based on previous purchase count
SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment
FROM customer;

-- Transactions and revenue generated by payment method
SELECT payment_method,
    COUNT(*) AS total_transactions,
    SUM(purchase_amount_usd) AS revenue_generated
FROM customer
GROUP BY payment_method
ORDER BY revenue_generated DESC;

-- Revenue and order count across seasons
SELECT season,
COUNT(*) AS total_orders,
SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;

-- Average spending based on purchase frequency in days
SELECT purchase_frequency_days, AVG(purchase_amount_usd) AS avg_spending
FROM customer
GROUP BY purchase_frequency_days
ORDER BY purchase_frequency_days;

-- Purchase distribution across gender and product category
SELECT gender, category,
COUNT(*) AS purchases
FROM customer
GROUP BY gender, category
ORDER BY gender, purchases DESC;

-- Ranking products within each category by purchase count
SELECT *
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
) ranked_products
WHERE rank_in_category <= 3;

-- Subscription distribution among repeat buyers
SELECT subscription_status,
COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Revenue and average spending grouped by age group
SELECT age_group,
SUM(purchase_amount_usd) AS total_revenue,
AVG(purchase_amount_usd) AS avg_spend
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


